# Generated by Django 4.2.3 on 2024-04-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone_no', models.CharField(max_length=50, verbose_name='Phone No')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('description', models.TextField()),
            ],
        ),
    ]
